const express = require("express");
const path = require("path");
const cors = require("cors");
const helmet = require("helmet");
const rateLimit = require("express-rate-limit");
const env = require("./config/env");

const app = express();

// Middlewares
app.use(
  helmet({
    contentSecurityPolicy: false,
    crossOriginEmbedderPolicy: false,
  })
);
app.use(
  cors({
    origin: env.CORS_ORIGINS.length > 0 ? env.CORS_ORIGINS : "*",
  })
);
app.use(express.json());

const limiter = rateLimit({
  windowMs: env.RATE_LIMIT_WINDOW_MS,
  max: env.RATE_LIMIT_MAX,
  message: { success: false, message: "Too many requests, please try again later." }
});

app.use("/api/contact", limiter, require("./routes/contact.routes"));
app.use("/api/newsletter-subscribe", limiter, require("./routes/newsletterRoutes"));

app.get("/api", (req, res) => {
  res.json({ 
    success: true, 
    message: "Latrics India API is running",
    version: "1.0.0",
    docs: "Contact/Newsletter endpoints active"
  });
});

app.get("/health", (req, res) => {
  res.json({ success: true, status: "UP", uptime: process.uptime() });
});

// ── Serve Frontend in Production ─────────────────────────────
// We point to the 'dist' folder generated by the frontend build in the root
const frontendDistPath = path.join(__dirname, "../../client/dist");
app.use(express.static(frontendDistPath));

// Wildcard route: send index.html for any non-API routes
// This allows React Router to handle page navigation
app.get("*", (req, res) => {
  res.sendFile(path.join(frontendDistPath, "index.html"));
});

// Error handling middleware
app.use((err, req, res, next) => {
  console.error("[ERROR]", err.stack);
  res.status(500).json({ success: false, message: "Internal server error" });
});

module.exports = app;
